// ============================================
// Chompi's Coffee Cup — app logic
// ============================================

let CAFES = [];
let BEANS = [];
let QUIZ_QUESTIONS = [];

// Load data from JSON files (generated by Decap CMS)
async function loadData() {
  try {
    const [cafesRes, beansRes, quizRes] = await Promise.all([
      fetch('data/cafes.json'),
      fetch('data/beans.json'),
      fetch('data/quiz.json')
    ]);
    CAFES = (await cafesRes.json()).items;
    BEANS = (await beansRes.json()).items;
    QUIZ_QUESTIONS = await quizRes.json();

    initUI();
  } catch (err) {
    console.error('Failed to load data', err);
    document.getElementById('cafe-grid').innerHTML =
      '<p style="color:var(--ink-soft);padding:2rem;text-align:center">Could not load data. Check the data/ folder.</p>';
  }
}

function initUI() {
  updateStats();
  populateHoodFilter();
  renderCafes();
  renderBeans();
  initMap();
}

// ============================================
// Stats
// ============================================
function updateStats() {
  document.getElementById('stat-cafes').textContent = CAFES.length;
  const uniqueRoasters = new Set(CAFES.map(c => c.roaster)).size;
  document.getElementById('stat-roasters').textContent = uniqueRoasters;
  document.getElementById('stat-beans').textContent = BEANS.length;
}

// ============================================
// Stars rendering
// ============================================
function stars(n) {
  const full = '★'.repeat(n);
  const empty = '<span class="empty">' + '★'.repeat(5 - n) + '</span>';
  return full + empty;
}

// ============================================
// Neighborhood filter
// ============================================
function populateHoodFilter() {
  const sel = document.getElementById('hood-filter');
  const hoods = ['All neighborhoods', ...new Set(CAFES.map(c => c.hood))];
  sel.innerHTML = hoods.map((h, i) =>
    `<option value="${i === 0 ? 'all' : h}">${h}</option>`
  ).join('');
  sel.addEventListener('change', (e) => renderCafes(e.target.value));
}

// ============================================
// Cafés
// ============================================
function renderCafes(filter = 'all') {
  const list = filter === 'all' ? CAFES : CAFES.filter(c => c.hood === filter);
  const grid = document.getElementById('cafe-grid');
  grid.innerHTML = list.map(c => `
    <article class="cafe-card" id="cafe-${slug(c.name)}">
      <div class="cafe-head">
        <div>
          <p class="cafe-hood">${c.hood}</p>
          <h3 class="cafe-name">${c.name}</h3>
          <p class="cafe-address">${c.address}</p>
        </div>
        <span class="price-tag">${c.price}</span>
      </div>
      <div class="ratings">
        <div class="rating">
          <span class="rating-label">Coffee</span>
          <span class="rating-stars">${stars(c.coffee)}</span>
        </div>
        <div class="rating">
          <span class="rating-label">Vibe</span>
          <span class="rating-stars">${stars(c.vibe)}</span>
        </div>
        <div class="rating">
          <span class="rating-label">Value</span>
          <span class="rating-stars">${stars(c.value)}</span>
        </div>
      </div>
      <p class="cafe-review">"${c.review}"</p>
      <div class="drink-tags">
        ${(c.drinks || []).map(d => `<span class="drink-tag">${d}</span>`).join('')}
      </div>
      <div class="cafe-foot">
        <p class="roaster-line">Roasted by <strong>${c.roaster}</strong></p>
        ${c.beanId ? `<button class="btn-sm" onclick="viewBean('${c.beanId}')">Shop these beans ↗</button>` : ''}
      </div>
    </article>
  `).join('');
}

function slug(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

// ============================================
// Beans
// ============================================
function renderBeans(highlightId = null) {
  const list = highlightId
    ? [...BEANS].sort((a, b) => (a.id === highlightId ? -1 : b.id === highlightId ? 1 : 0))
    : BEANS;

  const grid = document.getElementById('bean-grid');
  grid.innerHTML = list.map(b => `
    <article class="bean-card ${b.id === highlightId ? 'highlighted' : ''}" id="bean-${b.id}">
      ${b.id === highlightId ? '<span class="bean-badge">From your café</span>' : ''}
      <div class="bean-head">
        <div>
          <p class="bean-roaster">${b.roaster}</p>
          <h3 class="bean-name">${b.name}</h3>
        </div>
        <span class="bean-price">${b.price}</span>
      </div>
      <div class="bean-tags">
        <span class="bean-tag">${b.roast} roast</span>
        <span class="bean-tag">Acidity ${b.acidity}/5</span>
        <span class="bean-tag">Body ${b.body}/5</span>
        <span class="bean-tag">${b.origin}</span>
      </div>
      <p class="bean-notes">Notes: <strong>${(b.notes || []).join(', ')}</strong></p>
      <div class="bean-foot">
        <button class="btn-sm" onclick="showSimilar('${b.id}')">Similar beans</button>
        <a href="${b.url}" target="_blank" rel="noopener" class="btn-buy">Buy ↗</a>
      </div>
    </article>
  `).join('');
}

function viewBean(beanId) {
  renderBeans(beanId);
  const el = document.getElementById('bean-' + beanId);
  if (el) {
    el.scrollIntoView({ behavior: 'smooth', block: 'center' });
  } else {
    document.getElementById('beans').scrollIntoView({ behavior: 'smooth' });
  }
}

// ============================================
// Similar beans (rules-based matcher)
// ============================================
function similarityScore(target, candidate) {
  if (target.id === candidate.id) return -Infinity;
  let score = 0;
  // Roast level proximity
  score += (candidate.roast === target.roast) ? 4 : 0;
  // Acidity & body closeness (max 5 points each)
  score += 5 - Math.abs(candidate.acidity - target.acidity);
  score += 5 - Math.abs(candidate.body - target.body);
  // Shared tasting notes (3 points per shared note)
  const shared = (candidate.notes || []).filter(n => (target.notes || []).includes(n));
  score += shared.length * 3;
  return score;
}

function showSimilar(beanId) {
  const target = BEANS.find(b => b.id === beanId);
  if (!target) return;

  const similar = BEANS
    .map(b => ({ bean: b, score: similarityScore(target, b) }))
    .filter(s => s.score > -Infinity)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);

  const modal = document.createElement('div');
  modal.className = 'modal-overlay';
  modal.onclick = (e) => { if (e.target === modal) modal.remove(); };
  modal.innerHTML = `
    <div class="modal">
      <button class="modal-close" onclick="this.closest('.modal-overlay').remove()">×</button>
      <p class="eyebrow">Similar to</p>
      <h3 style="font-family: var(--font-display); font-size: 24px; font-weight: 500; margin: 0 0 1.5rem;">${target.name}</h3>
      ${similar.map(s => `
        <div style="padding: 1rem 0; border-top: 1px solid var(--line);">
          <div style="display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 4px;">
            <div>
              <p class="bean-roaster" style="margin: 0 0 2px;">${s.bean.roaster}</p>
              <p class="bean-name" style="margin: 0;">${s.bean.name}</p>
            </div>
            <span class="bean-price">${s.bean.price}</span>
          </div>
          <p class="bean-notes" style="margin: 6px 0 10px;">${s.bean.roast} · ${(s.bean.notes || []).join(', ')}</p>
          <a href="${s.bean.url}" target="_blank" rel="noopener" class="btn-buy">Buy ↗</a>
        </div>
      `).join('')}
    </div>
  `;
  document.body.appendChild(modal);
}

// ============================================
// Map
// ============================================
function initMap() {
  const map = L.map('leaflet-map', {
    zoomControl: true,
    scrollWheelZoom: false
  }).setView([42.350, -71.085], 13);

  // Clean, warm map tiles (Stadia Alidade Smooth — free for non-commercial, fallback to Carto)
  L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png', {
    attribution: '© OpenStreetMap contributors © CARTO',
    subdomains: 'abcd',
    maxZoom: 19
  }).addTo(map);

  const pins = [];
  CAFES.forEach(c => {
    if (!c.lat || !c.lng) return;

    const pinIcon = L.divIcon({
      className: 'coffee-pin-wrap',
      html: '<div class="coffee-pin"></div>',
      iconSize: [32, 32],
      iconAnchor: [16, 32]
    });

    const marker = L.marker([c.lat, c.lng], { icon: pinIcon }).addTo(map);
    marker.bindPopup(`
      <div class="map-popup">
        <p class="mp-hood">${c.hood} · ${c.price}</p>
        <p class="mp-name">${c.name}</p>
        <p class="mp-review">"${(c.review || '').slice(0, 100)}${(c.review || '').length > 100 ? '…' : ''}"</p>
        <a href="#cafe-${slug(c.name)}" class="mp-link" onclick="document.getElementById('cafe-${slug(c.name)}').scrollIntoView({behavior:'smooth'});">Read the full review →</a>
      </div>
    `);
    pins.push([c.lat, c.lng]);
  });

  // Fit bounds to all pins
  if (pins.length > 0) {
    map.fitBounds(pins, { padding: [40, 40] });
  }

  // Re-enable scroll-wheel zoom on click (better UX)
  map.on('click', () => map.scrollWheelZoom.enable());
}

// ============================================
// Quiz
// ============================================
let quizState = { step: 0, answers: [] };

function startQuiz() {
  quizState = { step: 0, answers: [] };
  document.getElementById('quiz-start').style.display = 'none';
  document.getElementById('quiz-results').style.display = 'none';
  document.getElementById('quiz-body').style.display = 'block';
  renderQuizStep();
}

function renderQuizStep() {
  const body = document.getElementById('quiz-body');
  const q = QUIZ_QUESTIONS[quizState.step];
  const progress = ((quizState.step + 1) / QUIZ_QUESTIONS.length) * 100;

  body.innerHTML = `
    <div class="quiz-progress">
      <span>Question ${quizState.step + 1} of ${QUIZ_QUESTIONS.length}</span>
      <div class="progress-bar"><div class="progress-fill" style="width:${progress}%"></div></div>
    </div>
    <h3 class="quiz-question">${q.question}</h3>
    <div class="quiz-options">
      ${q.options.map((o, i) => `
        <button class="quiz-option" onclick="answerQuiz(${i})">${o.label}</button>
      `).join('')}
    </div>
  `;
}

function answerQuiz(optIdx) {
  const opt = QUIZ_QUESTIONS[quizState.step].options[optIdx];
  quizState.answers.push(opt);
  quizState.step++;

  if (quizState.step >= QUIZ_QUESTIONS.length) {
    showQuizResults();
  } else {
    renderQuizStep();
  }
}

function showQuizResults() {
  document.getElementById('quiz-body').style.display = 'none';
  const results = document.getElementById('quiz-results');
  results.style.display = 'block';

  // Score every bean against the user's answers
  const scored = BEANS.map(b => {
    let score = 0;
    const reasons = [];

    quizState.answers.forEach(a => {
      // Acidity preference
      if (a.acidity === 'high' && b.acidity >= 4) { score += 3; reasons.push('bright acidity you want'); }
      if (a.acidity === 'low' && b.acidity <= 2) { score += 3; reasons.push('mellow acidity you want'); }
      if (a.acidity === 'mid' && b.acidity === 3) { score += 2; }

      // Body preference
      if (a.body === 'high' && b.body >= 4) { score += 3; reasons.push('full body you prefer'); }
      if (a.body === 'low' && b.body <= 2) { score += 3; reasons.push('lighter body you prefer'); }
      if (a.body === 'mid' && b.body === 3) { score += 2; }

      // Tasting notes
      if (a.notes) {
        const matches = (b.notes || []).filter(n =>
          a.notes.some(target => n.toLowerCase().includes(target.toLowerCase()))
        );
        if (matches.length > 0) {
          score += matches.length * 4;
          reasons.push(`${matches[0].toLowerCase()} notes match you`);
        }
      }

      // Roast level
      if (a.roast && Array.isArray(a.roast) && a.roast.includes(b.roast)) {
        score += 4;
        reasons.push(`${b.roast.toLowerCase()} roast fits you`);
      }
    });

    return { bean: b, score, reasons: [...new Set(reasons)].slice(0, 2) };
  }).sort((a, b) => b.score - a.score).slice(0, 3);

  results.innerHTML = `
    <div class="quiz-results-head">
      <h3>Your matches</h3>
      <p>Based on your taste, these three beans should land for you.</p>
    </div>
    ${scored.map((s, i) => `
      <div class="result-card ${i === 0 ? 'top' : ''}">
        <div class="result-head">
          <div>
            <p class="result-roaster">${s.bean.roaster}</p>
            <h4 class="result-name">${s.bean.name}</h4>
          </div>
          <span class="result-price">${s.bean.price}</span>
        </div>
        ${s.reasons.length ? `<p class="result-why">Why: ${s.reasons.join(' · ')}</p>` : ''}
        <div class="result-meta">
          <span>${s.bean.roast}</span>
          ${(s.bean.notes || []).slice(0, 3).map(n => `<span>${n}</span>`).join('')}
        </div>
        <div class="result-actions">
          <a href="${s.bean.url}" target="_blank" rel="noopener" class="btn-buy">Buy ↗</a>
          <button class="btn-sm" onclick="showSimilar('${s.bean.id}')">See similar</button>
        </div>
      </div>
    `).join('')}
    <div style="text-align:center; margin-top: 1.5rem;">
      <button class="btn-sm" style="color: var(--cream); border-color: rgba(245,239,227,0.4)" onclick="startQuiz()">Retake the quiz ↻</button>
    </div>
  `;
}

// Boot
document.addEventListener('DOMContentLoaded', loadData);
